#include "MirrorExternTypes.h"

namespace yae {

MIRROR_EXTERN_CLASS_DEFINITION(String);
MIRROR_EXTERN_CLASS_DEFINITION(Vector2);
MIRROR_EXTERN_CLASS_DEFINITION(Vector3);
MIRROR_EXTERN_CLASS_DEFINITION(Vector4);
MIRROR_EXTERN_CLASS_DEFINITION(Quaternion);
MIRROR_EXTERN_CLASS_DEFINITION(Matrix3);
MIRROR_EXTERN_CLASS_DEFINITION(Matrix4);

} // namespace yae
